### ISSUE TITLE
Raspberry Pi?

### ISSUE THREAD

**Issue by MTRNord** [mongodb-js/runner#79]
I wanted to run an parse server (which uses this node module) on an raspberry pi2. it did download mongodb (it says `✔ Downloaded MongoDB 3.2.7` ) but it was unable to connect to it. error is 
```
parse-server running on http://localhost:1337/parse
error: Uncaught internal server error. { [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
name: 'MongoError',
message: 'connect ECONNREFUSED 127.0.0.1:27017' } Error: connect ECONNREFUSED 127.0.0.1:27017
at Object.exports._errnoException (util.js:856:11)
at exports._exceptionWithHostPort (util.js:879:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1057:14)
```

Is there a way to fix this or have I to do something?

**Comment by lianyi** [comment]
can you verify if the mongo server is running locally?

**Comment by MTRNord** [comment]
how can i verify that?

**Comment by lianyi** [comment]
```
pi@raspberrypi ~ $ mongo
MongoDB shell version:  
connecting to: test
>
```

**Comment by MTRNord** [comment]
it says command not found :&

**Comment by MTRNord** [comment]
it seems the server was downloaded but not installed

**Comment by MTRNord** [comment]
When i want to start it manualy it says `bash: ./bin/mongod: cannot execute binary file`

**Comment by imlucas** [comment]
Hi @MTRNord,

It seems mongodb is downloaded and installed correctly (if you add `./root/.mongodb/versions/mongodb-3.2.7-linux-64/bin/` to your `$PATH` environment variable  @lianyi's command above will work).

Judging by your error message, mongodb is not running when you try to access the parse API (at http://localhost:1337/parse).  You'll need to start MongoDB separately or (more likely) configure the parse server app to read from a remote MongoDB deployment rather than one running locally on the Raspberry PI.  I'd recommend creating a new issue at https://github.com/parseplatform/parse-server to get this resolved as quickly as possible.

Thanks,
-Lucas

**Comment by MTRNord** [comment]
ok but thanks for support :)

**Comment by callmephilip** [comment]
Ran into exact same problem on Ubuntu 14.04.3 LTS
